language: node_js
node_js: stable

# 只监听 source 分支的改动
branches:
  only:
  - hexo

# 缓存依赖，节省持续集成时间
cache:
  yarn: true
  directories:
    - node_modules
    - themes

before_install:
- openssl aes-256-cbc -K $encrypted_9c865ccd0ee1_key -iv $encrypted_9c865ccd0ee1_iv
  -in .travis/github_blog.enc -out ~/.ssh/github_blog -d
- chmod 600 ~/.ssh/github_blog
- eval $(ssh-agent)
- ssh-add ~/.ssh/github_blog
- cp .travis/ssh_config ~/.ssh/config

# 修改本机 ssh 配置，防止秘钥认证过程影响自动部署
- mv -fv .travis/ssh-config ~/.ssh/config
- git config --global user.name "${USER.NAME}"
- git config --global user.email "${USER.EMAIL}"
# 赋予自动部署脚本可执行权限
- chmod +x .travis/deploy.sh
- npm install -g hexo-cli

install:
# 安装 Hexo 及其依赖
- npm install

script:
# 生成静态页面
- hexo clean
- hexo generate

after_success:
- .travis/deploy.sh
